INSERT INTO users (name, age, gender, province, educational_level, employment_status)
VALUES
('John Doe', 30, 'Male', 'Kigali', 'Bachelor', 'Employed'),
('Jane Doe', 25, 'Female', 'Southern Province', 'Masters', 'Unemployed'),
('Alex Mutoni', 22, 'Other', 'Western Province', 'Diploma', 'Student'),
('Jean Claude', 45, 'Male', 'Northern Province', 'Secondary', 'Self-employed'),
('Grace Uwase', 60, 'Female', 'Eastern Province', 'Primary', 'Retired'),
('Michel Ndahiro', 28, 'Male', 'Kigali', 'Bachelor', 'Employed'),
('Alice Mukamisha', 35, 'Female', 'Western Province', 'Secondary', 'Employed'),
('Emmanuel Ngirabega', 50, 'Male', 'Southern Province', 'Masters', 'Self-employed'),
('Martha Uwamariya', 40, 'Female', 'Northern Province', 'PhD', 'Employed'),
('Isaac Rukundo', 29, 'Male', 'Eastern Province', 'Bachelor', 'Unemployed'),
('Sophie Kamanzi', 32, 'Female', 'Kigali', 'Masters', 'Self-employed'),
('Claude Uwiringiyimana', 21, 'Male', 'Kigali', 'Secondary', 'Student'),
('Chantal Umuhoza', 45, 'Female', 'Southern Province', 'Primary', 'Retired'),
('Diane Iradukunda', 26, 'Female', 'Northern Province', 'Diploma', 'Employed'),
('Eric Mugisha', 37, 'Male', 'Eastern Province', 'Bachelor', 'Self-employed'),
('Rebecca Mutoni', 39, 'Female', 'Western Province', 'Masters', 'Employed'),
('Samuel Kayitesi', 30, 'Male', 'Kigali', 'Secondary', 'Employed'),
('Fiona Mutabazi', 31, 'Female', 'Southern Province', 'Bachelor', 'Unemployed'),
('Yvan Uwera', 23, 'Male', 'Kigali', 'Diploma', 'Student'),
('Tina Uwase', 41, 'Female', 'Eastern Province', 'PhD', 'Employed'),
('Henry Kamanzi', 50, 'Male', 'Western Province', 'Secondary', 'Self-employed'),
('Sasha Uwingabiye', 33, 'Female', 'Kigali', 'Masters', 'Employed'),
('Brian Mugabo', 29, 'Male', 'Northern Province', 'Bachelor', 'Unemployed'),
('Katherine Kabera', 28, 'Female', 'Southern Province', 'Diploma', 'Employed'),
('Michel Kalisa', 34, 'Male', 'Eastern Province', 'Masters', 'Self-employed'),
('Hannah Nyiramahoro', 50, 'Female', 'Western Province', 'PhD', 'Employed'),
('Aline Umutoni', 19, 'Female', 'Kigali', 'Secondary', 'Student'),
('Jean Bosco', 37, 'Male', 'Kigali', 'Bachelor', 'Employed'),
('Sophie Tuyishime', 40, 'Female', 'Southern Province', 'Primary', 'Self-employed'),
('Pierre Ntahobari', 22, 'Male', 'Kigali', 'Diploma', 'Unemployed'),
('Adeline Byusa', 41, 'Female', 'Western Province', 'PhD', 'Employed'),
('Vincent Mugenzi', 29, 'Male', 'Eastern Province', 'Masters', 'Unemployed'),
('Geraldine Uwase', 34, 'Female', 'Southern Province', 'Secondary', 'Self-employed'),
('Louis Uwimana', 26, 'Male', 'Northern Province', 'Bachelor', 'Employed'),
('Sylvie Byukusenge', 50, 'Female', 'Kigali', 'Secondary', 'Retired'),
('Patrick Kayijuka', 35, 'Male', 'Eastern Province', 'Masters', 'Employed'),
('Olga Uwase', 32, 'Female', 'Kigali', 'PhD', 'Self-employed'),
('Eric Habimana', 38, 'Male', 'Western Province', 'Secondary', 'Employed'),
('Doris Nyiransabimana', 24, 'Female', 'Southern Province', 'Bachelor', 'Student'),
('Emmanuel Ngabo', 27, 'Male', 'Kigali', 'Masters', 'Unemployed'),
('Fanny Nyirandikubwimana', 45, 'Female', 'Eastern Province', 'Primary', 'Self-employed'),
('Fabrice Murebwayire', 33, 'Male', 'Western Province', 'PhD', 'Employed'),
('Rose Uwase', 50, 'Female', 'Kigali', 'Diploma', 'Retired'),
('Jean Paul Kagame', 41, 'Male', 'Southern Province', 'Secondary', 'Self-employed'),
('Louise Umutoni', 36, 'Female', 'Northern Province', 'Masters', 'Self-employed'),
('Diane Imanishimwe', 27, 'Female', 'Kigali', 'Bachelor', 'Employed'),
('Thierry Niyonzima', 38, 'Male', 'Eastern Province', 'Secondary', 'Self-employed'),
('Vanessa Nyamwasa', 50, 'Female', 'Kigali', 'Diploma', 'Retired');